# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import simulation_pb2 as simulation__pb2


class SimulationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateAgent = channel.unary_unary(
        '/olamai.endpoints.simulation.Simulation/CreateAgent',
        request_serializer=simulation__pb2.CreateAgentRequest.SerializeToString,
        response_deserializer=simulation__pb2.Agent.FromString,
        )
    self.GetAgent = channel.unary_unary(
        '/olamai.endpoints.simulation.Simulation/GetAgent',
        request_serializer=simulation__pb2.GetAgentRequest.SerializeToString,
        response_deserializer=simulation__pb2.Agent.FromString,
        )
    self.DeleteAgent = channel.unary_unary(
        '/olamai.endpoints.simulation.Simulation/DeleteAgent',
        request_serializer=simulation__pb2.DeleteAgentRequest.SerializeToString,
        response_deserializer=simulation__pb2.Empty.FromString,
        )
    self.ActionAgent = channel.unary_unary(
        '/olamai.endpoints.simulation.Simulation/ActionAgent',
        request_serializer=simulation__pb2.ActionAgentRequest.SerializeToString,
        response_deserializer=simulation__pb2.Empty.FromString,
        )
    self.GetObservation = channel.unary_unary(
        '/olamai.endpoints.simulation.Simulation/GetObservation',
        request_serializer=simulation__pb2.GetObservationRequest.SerializeToString,
        response_deserializer=simulation__pb2.Observation.FromString,
        )
    self.CreateSpectator = channel.unary_stream(
        '/olamai.endpoints.simulation.Simulation/CreateSpectator',
        request_serializer=simulation__pb2.CreateSpectatorRequest.SerializeToString,
        response_deserializer=simulation__pb2.CellUpdate.FromString,
        )
    self.SubscribeSpectator = channel.unary_unary(
        '/olamai.endpoints.simulation.Simulation/SubscribeSpectator',
        request_serializer=simulation__pb2.SubscribeSpectatorRequest.SerializeToString,
        response_deserializer=simulation__pb2.Empty.FromString,
        )
    self.ResetWorld = channel.unary_unary(
        '/olamai.endpoints.simulation.Simulation/ResetWorld',
        request_serializer=simulation__pb2.Empty.SerializeToString,
        response_deserializer=simulation__pb2.Empty.FromString,
        )


class SimulationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateAgent(self, request, context):
    """Creates a new agent
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAgent(self, request, context):
    """Returns a specific agent
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteAgent(self, request, context):
    """Deletes an agent
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ActionAgent(self, request, context):
    """Perform agent action
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetObservation(self, request, context):
    """Returns a specific book.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateSpectator(self, request, context):
    """Start a spectation stream
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SubscribeSpectator(self, request, context):
    """Subscribe a spectator to a region
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ResetWorld(self, request, context):
    """Reset the world
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SimulationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateAgent': grpc.unary_unary_rpc_method_handler(
          servicer.CreateAgent,
          request_deserializer=simulation__pb2.CreateAgentRequest.FromString,
          response_serializer=simulation__pb2.Agent.SerializeToString,
      ),
      'GetAgent': grpc.unary_unary_rpc_method_handler(
          servicer.GetAgent,
          request_deserializer=simulation__pb2.GetAgentRequest.FromString,
          response_serializer=simulation__pb2.Agent.SerializeToString,
      ),
      'DeleteAgent': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteAgent,
          request_deserializer=simulation__pb2.DeleteAgentRequest.FromString,
          response_serializer=simulation__pb2.Empty.SerializeToString,
      ),
      'ActionAgent': grpc.unary_unary_rpc_method_handler(
          servicer.ActionAgent,
          request_deserializer=simulation__pb2.ActionAgentRequest.FromString,
          response_serializer=simulation__pb2.Empty.SerializeToString,
      ),
      'GetObservation': grpc.unary_unary_rpc_method_handler(
          servicer.GetObservation,
          request_deserializer=simulation__pb2.GetObservationRequest.FromString,
          response_serializer=simulation__pb2.Observation.SerializeToString,
      ),
      'CreateSpectator': grpc.unary_stream_rpc_method_handler(
          servicer.CreateSpectator,
          request_deserializer=simulation__pb2.CreateSpectatorRequest.FromString,
          response_serializer=simulation__pb2.CellUpdate.SerializeToString,
      ),
      'SubscribeSpectator': grpc.unary_unary_rpc_method_handler(
          servicer.SubscribeSpectator,
          request_deserializer=simulation__pb2.SubscribeSpectatorRequest.FromString,
          response_serializer=simulation__pb2.Empty.SerializeToString,
      ),
      'ResetWorld': grpc.unary_unary_rpc_method_handler(
          servicer.ResetWorld,
          request_deserializer=simulation__pb2.Empty.FromString,
          response_serializer=simulation__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'olamai.endpoints.simulation.Simulation', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
